# Project: TrainSystem
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Date.o Passenger.o SeatsAL.o TrainLink.o TrainLL.o TrainSystem.o WaitingList.o
LINKOBJ  = Date.o Passenger.o SeatsAL.o TrainLink.o TrainLL.o TrainSystem.o WaitingList.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TrainSystem.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Date.o: Date.cpp
	$(CPP) -c Date.cpp -o Date.o $(CXXFLAGS)

Passenger.o: Passenger.cpp
	$(CPP) -c Passenger.cpp -o Passenger.o $(CXXFLAGS)

SeatsAL.o: SeatsAL.cpp
	$(CPP) -c SeatsAL.cpp -o SeatsAL.o $(CXXFLAGS)

TrainLink.o: TrainLink.cpp
	$(CPP) -c TrainLink.cpp -o TrainLink.o $(CXXFLAGS)

TrainLL.o: TrainLL.cpp
	$(CPP) -c TrainLL.cpp -o TrainLL.o $(CXXFLAGS)

TrainSystem.o: TrainSystem.cpp
	$(CPP) -c TrainSystem.cpp -o TrainSystem.o $(CXXFLAGS)

WaitingList.o: WaitingList.cpp
	$(CPP) -c WaitingList.cpp -o WaitingList.o $(CXXFLAGS)
